#!/usr/bin/python3

import sys
import os
sys.path.insert(0, os.getcwd())
import unittest
import test_e

if __name__=="__main__":

  suite = unittest.defaultTestLoader.loadTestsFromModule(test_e)
  unittest.TextTestRunner().run(suite)
