#!/usr/bin/python3

import sys
import os
sys.path.insert(0, os.getcwd())
import unittest
import test_m

if __name__=="__main__":
  suite = unittest.defaultTestLoader.loadTestsFromModule(test_m)
  unittest.TextTestRunner().run(suite)
